name: Build DEV Apk

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '21'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build app
        run: |
          rm -f keystore.jks || true
          echo ${{ secrets.SIGNING_KEY }} | base64 -d > keystore.jks
          ./gradlew :app:assembleDev
        env:
          KEYSTORE_PATH: "../keystore.jks"
          KEYSTORE_PASSWORD: ${{ secrets.KEY_STORE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
      - name: Get APK file name
        id: get-apk-name
        run: |
          APK=$(basename ./app/build/outputs/apk/dev/*.apk)
          APK_NAME=${APK%.apk}
          echo "APK 文件名为: ${APK_NAME}"
          echo "APK_NAME=${APK_NAME}" >> $GITHUB_ENV
      - name: Upload android artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.APK_NAME }}
          path: ./app/build/outputs/apk/dev/*.apk
      - name: Configure Git
        run: |
          git config --global user.name "dongdong-gc"  # 替换为你的 Gitee 用户名
          git config --global user.email "2574822036@qq.com"  # 替换为你的邮箱

      - name: Prepare Gitee Folder
        run: |
          mkdir -p gitee-repo/dev
      # 下载 commit_history.json 文件
      - name: Download commit_history.json
        env:
          GITEE_TOKEN: ${{ secrets.GITEE_TOKEN }}
        run: |
          wget https://gitee.com/dongdong-gc/hyper-star-updater/raw/main/dev/head_commit.txt -O last_head_commit.text
          wget https://gitee.com/dongdong-gc/hyper-star-updater/raw/main/dev/apk_name.txt -O last_apk_name.text

      - name: Copy APK and metadata to Gitee folder
        run: |
          # 写入当前提交信息到 head_commit.txt
          echo "${{ env.APK_NAME }}" > gitee-repo/apk_name.txt
          echo "${{ github.event.head_commit.message }}" > gitee-repo/dev/head_commit.txt
  
          if [ ! -f gitee-repo/dev/commit_history.json ]; then
            echo "[]" > gitee-repo/dev/commit_history.json
          fi

          # 获取当前提交的信息并以 JSON 格式追加到文件中
          LAST_HEAD_COMMIT=$(cat last_head_commit.text)
          LAST_APK_NAME=$(cat last_apk_name.text)
          
          # 使用 jq 工具追加 JSON 对象
          jq "[{\"apk_name\": \"${LAST_APK_NAME}\", \"commit_message\": \"${LAST_HEAD_COMMIT}\"}] + ." \
          gitee-repo/dev/commit_history.json > gitee-repo/dev/commit_history.json.tmp && \
          mv gitee-repo/dev/commit_history.json.tmp gitee-repo/dev/commit_history.json
        
          # 将 APK 文件复制到目标文件夹
          cp ./app/build/outputs/apk/dev/*.apk gitee-repo/dev/
          mv gitee-repo/apk_name.txt gitee-repo/dev/  # 将文件名文件移动到目标文件夹

      - name: Push to Gitee
        run: |
          cd gitee-repo
          git init
          git remote add origin https://oauth2:${{ secrets.GITEE_TOKEN }}@gitee.com/dongdong-gc/hyper-star-updater.git
          git add .
          git commit -m "Sync APK and metadata from GitHub"
          git branch -M main
          git push -u origin main --force

      - name: Post to Telegram ci channel
        if: ${{ success() && github.event_name != 'pull_request' && github.ref == 'refs/heads/master' && github.ref_type != 'tag' }}
        env:
          CHANNEL_ID: ${{ secrets.CHANNEL_ID }}
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          COMMIT_MESSAGE: |+
            New CI from HyperStar
          
            ```
            ${{ github.event.head_commit.message }}
            ```
        run: |
          if [ ! -z "${{ secrets.BOT_TOKEN }}" ]; then
            export DEV=$(find ./app/build/outputs/apk/dev -name "*.apk")
            ESCAPED=`python3 -c 'import json,os,urllib.parse; print(urllib.parse.quote(json.dumps(os.environ["COMMIT_MESSAGE"])))'`
            curl -v "https://api.telegram.org/bot${BOT_TOKEN}/sendMediaGroup?chat_id=${CHANNEL_ID}&media=%5B%7B%22type%22:%22document%22,%20%22media%22:%22attach://dev%22,%22parse_mode%22:%22MarkdownV2%22,%22caption%22:${ESCAPED}%7D%5D" -F dev="@${DEV}"
          fi
